version: '3.9'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME: admin
      - MONGO_INITDB_ROOT_PASSWORD: rJGPIIrBV6YhGHeF
      - MONGO_INITDB_DATABASE: moviesDB
  backendapp:
    build: .
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://admin:rJGPIIrBV6YhGHeF@mongo:27017/moviesDB
    depends_on:
      - mongodb
